version: 0.2
phases:
   pre_build:
    commands:
      - aws --version
      - sam package --template-file template.yml --output-template-file package.yml --s3-bucket my-bucket-flask
      - sam package --template-file template2.yml --output-template-file package2.yml --s3-bucket my-bucket-flask
      - sam package --template-file template3.yml --output-template-file package3.yml --s3-bucket my-bucket-flask
      - sam deploy --template-file package.yml --stack-name sam1 
      - sam deploy --template-file package2.yml --stack-name sam2
      - sam deploy --template-file package3.yml --stack-name sam3
  
