version: 0.2
phases:
   pre_build:
    commands:
      - aws --version
      - sam package --template-file template.yml --output-template-file package.yml --s3-bucket my-bucket-flask
      - sam deploy --template-file package.yml --stack-name sam --capabilities CAPABILITY_IAM
