version: 0.2
phases:
   pre_build:
    commands:
      - aws --version
      - sam package --template-file template.yml --output-template-file package.yml --s3-bucket sam-git-bucket
      - sam deploy --template-file package.yml --stack-name sam-test-deploy --capabilities CAPABILITY_IAM
