AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  samtemplate1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: arn:aws:iam::406067944890:role/test-lambda
  samtemplate2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      Role: arn:aws:iam::406067944890:role/test-lambda
  samtemplate3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python2.7
      Role: arn:aws:iam::406067944890:role/test-lambda      
